[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "opencv-python>=4.11.0.86",
    "pandas>=2.2.3",
    "pyzbar>=0.1.9",
    "streamlit>=1.42.0",
    "twilio>=9.4.4",
]
